import type { Meta, StoryObj } from "@storybook/react";
import { ListTemplate } from "@components/templates/ListTemplate";

const items = [
  { title: "Design Review", subtitle: "Discuss Liquid Glass tokens" },
  { title: "QA Sync", subtitle: "Verify Button variants" },
  { title: "Roadmap", subtitle: "Plan AI Conversation" },
];

type MeetingItem = (typeof items)[number];

const renderMeetingItem = (item: unknown) => {
  const meeting = item as MeetingItem;
  return (
    <div style={{ padding: "1rem", borderRadius: "1rem", background: "rgba(255,255,255,0.85)" }}>
      <strong>{meeting.title}</strong>
      <p style={{ margin: 0, color: "rgba(0,0,0,0.55)" }}>{meeting.subtitle}</p>
    </div>
  );
};

const groups = [
  { title: "Today", items },
  { title: "Tomorrow", items: items.slice(0, 2) },
];

const meta = {
  title: "Templates/ListTemplate",
  component: ListTemplate,
  parameters: {
    layout: "centered",
    backgrounds: { default: "light" },
  },
  tags: ["autodocs"],
  args: {
    title: "Meetings",
    description: "Schedule generated by Apple Intelligence",
    renderItem: renderMeetingItem,
  },
} satisfies Meta<typeof ListTemplate>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Flat: Story = {
  args: {
    items,
    searchable: true,
  },
};

export const Grouped: Story = {
  args: {
    groups,
    searchable: true,
    refreshable: true,
  },
};
